export const productRows = [
  {
    name: "ASOS Ridley High Waist",
    price: "$79.49",
    qty: 82,
    amount: "$6,518.18",
  },
  {
    name: "Marco Lightweight Shirt",
    price: "$128.50",
    qty: 37,
    amount: "$4,754.50",
  },
  { name: "Half Sleeve Shirt", price: "$39.99", qty: 64, amount: "$2,559.36" },
  {
    name: "Lightweight Jacket",
    price: "$20.00",
    qty: 184,
    amount: "$3,680.00",
  },
  { name: "Marco Shoes", price: "$79.49", qty: 64, amount: "$1,965.81" },
];

export const stats = [
  { id: "customers", title: "Customers", value: "3,781", sub: "+11.01%" },
  { id: "orders", title: "Orders", value: "1,219", sub: "-0.03%" },
  { id: "revenue", title: "Revenue", value: "$695", sub: "+15.03%" },
  { id: "growth", title: "Growth", value: "30.1%", sub: "+6.08%" },
];

export const activities = [
  { id: 1, text: "You have a bug that needs fixing", time: "Just now" },
  { id: 2, text: "New user registered", time: "59 minutes ago" },
  { id: 3, text: "You have a bug that needs fixing", time: "12 hours ago" },
];

export const contacts = [
  {
    id: 1,
    name: "Natali Craig",
    role: "Owner",
    avatar: "/avatars/avatar1.png",
  },
  {
    id: 2,
    name: "Drew Cano",
    role: "Admin",
    avatar: "/avatars/avatar2.png",
  },
  {
    id: 3,
    name: "Orlando Diggs",
    role: "Member",
    avatar: "/avatars/avatar3.png",
  },
  {
    id: 4,
    name: "Andi Lane",
    role: "Member",
    avatar: "/avatars/avatar4.png",
  },
  {
    id: 5,
    name: "Kate Morrison",
    role: "Admin",
    avatar: "/avatars/avatar5.png",
  },
  {
    id: 6,
    name: "Koray Okumus",
    role: "Member",
    avatar: "/avatars/avatar6.png",
  },
];

export const notifications = [
  {
    id: 1,
    icon: "",
    text: "You have a bug that needs attention",
    time: "Just now",
  },
  {
    id: 2,
    icon: "",
    text: "New user registered",
    time: "59 minutes ago",
  },
  {
    id: 3,
    icon: "",
    text: "You have a bug that needs attention",
    time: "12 hours ago",
  },
  {
    id: 4,
    icon: "",
    text: "Andi Lane subscribed to you",
    time: "Today, 11:59 AM",
  },
];

export const rows = [
  {
    id: "#CM9801",
    user: { name: "Natali Craig", avatar: "/avatars/a1.png" },
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
  },
  {
    id: "#CM9802",
    user: { name: "Kate Morrison", avatar: "/avatars/a2.png" },
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
  },
  {
    id: "#CM9803",
    user: { name: "Drew Cano", avatar: "/avatars/a3.png" },
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
  },
  {
    id: "#CM9804",
    user: { name: "Orlando Diggs", avatar: "/avatars/a4.png" },
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Approved",
  },
  {
    id: "#CM9805",
    user: { name: "Andi Lane", avatar: "/avatars/a5.png" },
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
  },

  // ---- new mock rows below ----

  {
    id: "#CM9806",
    user: { name: "James Carter", avatar: "/avatars/a6.png" },
    project: "SaaS Platform UI",
    address: "Baker Street Houston",
    date: "2 days ago",
    status: "In Progress",
  },
  {
    id: "#CM9807",
    user: { name: "Emily Stone", avatar: "/avatars/a7.png" },
    project: "E-Commerce Backend",
    address: "Hillcrest New York",
    date: "3 days ago",
    status: "Pending",
  },
  {
    id: "#CM9808",
    user: { name: "Michael Foster", avatar: "/avatars/a8.png" },
    project: "Mobile App UI",
    address: "Crescent Road Phoenix",
    date: "Last week",
    status: "Complete",
  },
  {
    id: "#CM9809",
    user: { name: "Sophia Turner", avatar: "/avatars/a9.png" },
    project: "Analytics Dashboard",
    address: "River Street Miami",
    date: "Last week",
    status: "Approved",
  },
  {
    id: "#CM9810",
    user: { name: "Daniel White", avatar: "/avatars/a10.png" },
    project: "Portfolio Site",
    address: "Grand Avenue Denver",
    date: "Jan 30, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9811",
    user: { name: "Oliver Brooks", avatar: "/avatars/a11.png" },
    project: "Inventory Manager",
    address: "Sunset Blvd Dallas",
    date: "2 weeks ago",
    status: "Pending",
  },
  {
    id: "#CM9812",
    user: { name: "Ava Collins", avatar: "/avatars/a12.png" },
    project: "Marketing Dashboard",
    address: "Elm Road Seattle",
    date: "3 weeks ago",
    status: "Complete",
  },
  {
    id: "#CM9813",
    user: { name: "Henry Scott", avatar: "/avatars/a13.png" },
    project: "HR Portal",
    address: "Oak Ridge Atlanta",
    date: "Feb 12, 2023",
    status: "Approved",
  },
  {
    id: "#CM9814",
    user: { name: "Ella Bennett", avatar: "/avatars/a14.png" },
    project: "School LMS UI",
    address: "Kingston Road Boston",
    date: "Feb 10, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9815",
    user: { name: "Lucas Walker", avatar: "/avatars/a15.png" },
    project: "Docs System",
    address: "Highland San Diego",
    date: "3 weeks ago",
    status: "In Progress",
  },
  {
    id: "#CM9816",
    user: { name: "Grace Hill", avatar: "/avatars/a16.png" },
    project: "Banking Portal",
    address: "Greenwood Austin",
    date: "1 month ago",
    status: "Pending",
  },
  {
    id: "#CM9817",
    user: { name: "Jack Reed", avatar: "/avatars/a17.png" },
    project: "Crypto Wallet UI",
    address: "Pine Street Orlando",
    date: "1 month ago",
    status: "Complete",
  },
  {
    id: "#CM9818",
    user: { name: "Chloe Adams", avatar: "/avatars/a18.png" },
    project: "Food Delivery App",
    address: "Maple Avenue Detroit",
    date: "1 month ago",
    status: "Approved",
  },
  {
    id: "#CM9819",
    user: { name: "Ethan Ward", avatar: "/avatars/a19.png" },
    project: "Healthcare Dashboard",
    address: "Ocean Drive Tampa",
    date: "2 months ago",
    status: "Rejected",
  },
  {
    id: "#CM9820",
    user: { name: "Mia Brooks", avatar: "/avatars/a20.png" },
    project: "Billing System",
    address: "Harbor Street Portland",
    date: "2 months ago",
    status: "In Progress",
  },
  {
    id: "#CM9821",
    user: { name: "Noah Hayes", avatar: "/avatars/a21.png" },
    project: "Workflow Automation",
    address: "Central Park Kansas",
    date: "2 months ago",
    status: "Pending",
  },
  {
    id: "#CM9822",
    user: { name: "Lily Cooper", avatar: "/avatars/a22.png" },
    project: "Support Ticket UI",
    address: "Liberty Street Chicago",
    date: "3 months ago",
    status: "Complete",
  },
  {
    id: "#CM9823",
    user: { name: "Benjamin Adams", avatar: "/avatars/a23.png" },
    project: "Employee Portal",
    address: "Canyon Road Memphis",
    date: "3 months ago",
    status: "Approved",
  },
  {
    id: "#CM9824",
    user: { name: "Harper Lewis", avatar: "/avatars/a24.png" },
    project: "Finance Dashboard",
    address: "Mountain View Raleigh",
    date: "3 months ago",
    status: "Rejected",
  },
  {
    id: "#CM9825",
    user: { name: "Logan Rivera", avatar: "/avatars/a25.png" },
    project: "Booking Engine",
    address: "Valley Lane Tucson",
    date: "4 months ago",
    status: "Complete",
  },
];

export const statusColors = {
  "In Progress": "#8A8CD9",
  Complete: "#4AA785",
  Pending: "#59A8D4",
  Approved: "#FFC555",
  Rejected: "#1C1C1C66",
};
